#
runtime: php72
#runtime: php55
#api_version: 1
#threadsafe: yes
#env: flex
automatic_scaling:
  max_instances: 1

#entrypoint: serve public/index.php

#handlers:
#- url: .*
#  script: public/index.php
handlers:
- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public/favicon\.ico
- url: /assets
  static_dir: public/assets
- url: /css
  static_dir: public/css
- url: /js
  static_dir: public/js
- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots\.txt
- url: /ads.txt
  static_files: public/ads.txt
  upload: public/ads.txt

#env_variables:
#  # The following values are to be replaced by information from the output of
#  # 'gcloud endpoints services deploy swagger.json' command.
#  ENDPOINTS_SERVICE_NAME: koujinoapps-hrd.appspot.com
#  ENDPOINTS_SERVICE_VERSION: 2019-04-08r4

#endpoints_api_service:
#  # This is a template. Use the deploy_app.sh script to deploy this app.
#  name: koujinoapps-hrd.appspot.com
#  rollout_strategy: managed
